fix: Changed kubeVersion requirement
Required to be able to run helm charts against EKS, GKE - to avoid errors like this:

Error: chart requires kubeVersion: >=1.17.0 which is incompatible with Kubernetes v1.19.6-eks-49a6c0